<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RacingGameCasaEngine</RootNamespace>
    <AssemblyName>RacingGameCasaEngine</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
    <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1605</WarningsNotAsErrors>
    <NoWarn>$(NoWarn);NU1605</NoWarn>
    <RestoreNoWarn>$(RestoreNoWarn);NU1605</RestoreNoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FontStashSharp.MonoGame" Version="1.5.4" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.2.1105" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CasaEngine\CasaEngine\CasaEngine.csproj" />
    <ProjectReference Include="..\CasaEngine\MGUI\MGUI.Core\MGUI.Core.csproj" />
    <ProjectReference Include="..\CasaEngine\MGUI\MGUI.Shared\MGUI.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Content\AssetInfos.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\CasaEngine\CasaEngine\Content\Fonts\tahoma.ttf" Link="Content\Fonts\tahoma.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\RacingGame\Content\Textures\*.*" Link="Content\Textures\%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\RacingGame\Content\*.Track" Link="Content\Tracks\%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\RacingGame\Content\LandscapeHeights.data" Link="Content\LandscapeHeights.data">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\RacingGame\Content\*.CombiModel" Link="Content\Models\%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\RacingGame\Content\Models\*.X" Link="Content\Models\%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="RestoreDotnetTools" BeforeTargets="Restore">
    <Message Text="Restoring dotnet tools" Importance="High" />
    <Exec Command="dotnet tool restore" />
  </Target>
</Project>