<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RacingGameCasaEngine</RootNamespace>
    <AssemblyName>RacingGameCasaEngine</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FontStashSharp.MonoGame" Version="1.3.10" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.2.1105" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CasaEngine\CasaEngine\CasaEngine.csproj" />
    <ProjectReference Include="..\MGUI\MGUI.Core\MGUI.Core.csproj" />
    <ProjectReference Include="..\MGUI\MGUI.Shared\MGUI.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Content\AssetInfos.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\CasaEngine\CasaEngine\Content\Fonts\tahoma.ttf" Link="Content\Fonts\tahoma.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\RacingGame\Content\Textures\buttons.png" Link="Content\Textures\buttons.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\RacingGame\Content\Textures\background.png" Link="Content\Textures\background.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="RestoreDotnetTools" BeforeTargets="Restore">
    <Message Text="Restoring dotnet tools" Importance="High" />
    <Exec Command="dotnet tool restore" />
  </Target>
</Project>