<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CasaEngine\MGUI\MGUI.Core\MGUI.Core.csproj" />
    <ProjectReference Include="..\CasaEngine\MGUI\MGUI.FontStashSharp\MGUI.FontStashSharp.csproj" />
    <ProjectReference Include="..\CasaEngine\MGUI\MGUI.MonoGame.LegacyRenderer\MGUI.MonoGame.LegacyRenderer.csproj" />
    <ProjectReference Include="..\CasaEngine\MGUI\MGUI.Shared\MGUI.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="UI\MGUI\Themes\RacingGameButtonThemes.xaml" />
    <EmbeddedResource Include="UI\MGUI\Themes\RacingGameButtonThemes.xaml">
      <LogicalName>RacingGame.UI.MGUI.Themes.RacingGameButtonThemes.xaml</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>